language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - rbx-2
gemfile:
 - gemfiles/rails3/Gemfile
 - gemfiles/rails4/Gemfile
matrix:
  allow_failures:
    - rvm: 1.9.2
      gemfile: gemfiles/rails4/Gemfile
